//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBC
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderNumber { get; set; }
        public int PalletNumber { get; set; }
        public int OrderLineNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Acknowledgement { get; set; }
    
        internal virtual Order Order { get; set; }
        public virtual Pallet Pallet { get; set; }
    }
}
